version: '3'
services:
    api-gateway:
        image: pomper/api-gateway
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - API_GATEWAY_PORT=3000
            - AUTH_PORT=3001
            - USER_PORT=3002
            - ACCOUNTS_PORT=3003
            - TRANSACTION_PORT=3004
            - TOPUP_PORT=3005
            - NATS_URL=nats://nats-srv:4222
            - API_GATEWAY_SERVICE_URL=http://api-gateway-srv:3000/
            - AUTH_SERVICE_URL=http://auth-srv:3001/api/v1/auth
            - USER_SERVICE_URL=http://users-srv:3002/api/v1/users
            - ACCOUNT_SERVICE_URL=http://accounts-srv:3003/api/v1/accounts
            - TRANSACTION_SERVICE_URL=http://transaction-srv:3004/api/v1/transactions
            - TOPUP_SERVICE_URL=http://topup-srv:3005/api/v1/topup
            - JWT_SECRET=ppkidtuengkunkhao
            - JWT_EXPIRES_IN=90d
            - JWT_COOKIE_EXPIRES_IN=90
        depends_on:
            - nats
            - auth
            - users
            - auth-mongo
            - users-mongo

    auth:
        image: pomper/auth
        ports:
            - '3001:3001'
        environment:
            - DATABASE_PROD=mongodb://auth-mongo-srv:27017/auth
        depends_on:
            - auth-mongo
            - nats

    auth-mongo:
        image: mongo
        ports:
            - '27017:27017'

    nats:
        image: nats:alpine
        ports:
            - '4222:4222'

    users:
        image: pomper/users
        ports:
            - '3002:3002'
        environment:
            - DATABASE_PROD=mongodb://users-mongo-srv:27017/users
        depends_on:
            - users-mongo
            - nats

    users-mongo:
        image: mongo
        ports:
            - '27017:27017'

    ganache:
        image: trufflesuite/ganache-cli
        ports:
            - '7545:7545'
        command:
            - -h 0.0.0.0
            - -p 7545
            - -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
            - -i 5777

    crypto-service:
        build: ./crypto
        ports:
            - '3006:3006'
        depends_on:
            - ganache
        environment:
            - RPC_URL=http://ganache:7545
            - NODE_ENV=development
            - API_GATEWAY_PORT=3000
            - AUTH_PORT=3001
            - USER_PORT=3002
            - ACCOUNTS_PORT=3003
            - TRANSACTION_PORT=3004
            - TOPUP_PORT=3005
            - CRYPTO_PORT=3006
            - NATS_URL=nats://nats-srv:4222
            - API_GATEWAY_SERVICE_URL=http://api-gateway-srv:3000/
            - AUTH_SERVICE_URL=http://auth-srv:3001/api/v1/auth
            - USER_SERVICE_URL=http://users-srv:3002/api/v1/users
            - ACCOUNT_SERVICE_URL=http://accounts-srv:3003/api/v1/accounts
            - TRANSACTION_SERVICE_URL=http://transaction-srv:3004/api/v1/transactions
            - TOPUP_SERVICE_URL=http://topup-srv:3005/api/v1/topup
            # - CRYPTO_SERVICE_URL=http://localhost:3006/

    # Add any additional services as needed following this pattern

networks:
    default:
        driver: bridge
