apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: crypto-service
  name: crypto-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: crypto-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: crypto-service
    spec:
      containers:
        - env:
            - name: ACCOUNTS_PORT
              value: "3003"
            - name: ACCOUNT_SERVICE_URL
              value: http://accounts-srv:3003/api/v1/accounts
            - name: API_GATEWAY_PORT
              value: "3000"
            - name: API_GATEWAY_SERVICE_URL
              value: http://api-gateway-srv:3000/
            - name: AUTH_PORT
              value: "3001"
            - name: AUTH_SERVICE_URL
              value: http://auth-srv:3001/api/v1/auth
            - name: CRYPTO_PORT
              value: "3006"
            - name: NATS_URL
              value: nats://nats-srv:4222
            - name: NODE_ENV
              value: development
            - name: RPC_URL
              value: http://ganache:7545
            - name: TOPUP_PORT
              value: "3005"
            - name: TOPUP_SERVICE_URL
              value: http://topup-srv:3005/api/v1/topup
            - name: TRANSACTION_PORT
              value: "3004"
            - name: TRANSACTION_SERVICE_URL
              value: http://transaction-srv:3004/api/v1/transactions
            - name: USER_PORT
              value: "3002"
            - name: USER_SERVICE_URL
              value: http://users-srv:3002/api/v1/users
          image: crypto-service
          name: crypto-service
          ports:
            - containerPort: 3006
              protocol: TCP
      restartPolicy: Always
