apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            initContainers:
                - name: wait-for-nats
                  image: busybox
                  command: ['sh', '-c', 'until nc -zv nats-srv 4222; do echo "waiting for NATS"; sleep 2; done']
                - name: wait-for-mongo
                  image: busybox
                  command: ['sh', '-c', 'until nc -zv auth-mongo-srv 27017; do echo "waiting for MongoDB"; sleep 2; done']
            containers:
                - name: auth
                  image: pomper/auth
                  env:
                      - name: DATABASE_PROD
                        value: 'mongodb://auth-mongo-srv:27017/auth'
                  envFrom:
                      - configMapRef:
                            name: config-mapping
---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 3001
          targetPort: 3001
