apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: users
    template:
        metadata:
            labels:
                app: users
        spec:
            initContainers:
                - name: wait-for-nats
                  image: busybox
                  command: ['sh', '-c', 'until nc -zv nats-srv 4222; do echo "waiting for NATS"; sleep 2; done']
                - name: wait-for-users-mongo
                  image: busybox
                  command: ['sh', '-c', 'until nc -zv users-mongo-srv 27017; do echo "waiting for MongoDB"; sleep 2; done']
            containers:
                - name: users
                  image: pomper/users
                  env:
                      - name: DATABASE_PROD
                        value: 'mongodb://users-mongo-srv:27017/users'
                  envFrom:
                      - configMapRef:
                            name: config-mapping
---
apiVersion: v1
kind: Service
metadata:
    name: users-srv
spec:
    selector:
        app: users
    ports:
        - name: users
          protocol: TCP
          port: 3002
          targetPort: 3002
