name: CI/CD Pipeline

on:
  push:  
    branches:
      - '**'  # This will trigger on any branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      # run: npm run install
      run: ls
 
    # - name: Run tests
    #   run: npm test
    - name: Make build.sh executable
      run: chmod +x ./build.sh

    - name: Build project
      run: ./build.sh
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Deploy to production
  #     run: |
  #       echo "Deploying to production..."
  #       # Add your deployment commands here